# Default config:
[API]
  ListenAddress = "/ip4/0.0.0.0/tcp/1234/http"
  RemoteListenAddress = ""
  Timeout = "30s"
#
[Libp2p]
  ListenAddresses = ["/ip4/0.0.0.0/tcp/0"]
#  AnnounceAddresses = []
#  NoAnnounceAddresses = []
#  ConnMgrLow = 150
#  ConnMgrHigh = 180
#  ConnMgrGrace = "20s"
#
[Pubsub]
#  Bootstrapper = false
#  RemoteTracer = "/dns4/pubsub-tracer.filecoin.io/tcp/4001/p2p/QmTd6UvR47vUidRNZ1ZKXHrAFhqTJAD27rKL9XYghEKgKX"
#
[Client]
#  UseIpfs = false
#  IpfsMAddr = ""
#  IpfsUseForRetrieval = false
#
[Metrics]
#  Nickname = ""
#  HeadNotifs = false
#
[Wallet]
#  RemoteBackend = ""
#  EnableLedger = false
#  DisableLocal = false

[Checkpoint]
  Fee = 0.01
  BitcoinHost="http://btc-rpc:18332"
  PublicKey="66a554b8af6719851a936b0afc29dc59c3678f0e3f0b7bb081c57c5b77ad48ff"
  MinioHost = "minio:9000"
  MinioAccessKeyID = "sarah"
  MinioSecretAccessKey = "123secure"
  MinioBucketName = "eudico"
